export const GET_WAREHOUSE_REQUEST = "GET_WAREHOUSE_REQUEST";
export const GET_WAREHOUSE_FAILURE = "GET_WAREHOUSE_FAILURE";
export const GET_WAREHOUSE_SUCCESS = "GET_WAREHOUSE_SUCCESS";

export const EDIT_ITEMS_REQUEST = "EDIT_ITEMS_REQUEST";
export const EDIT_ITEMS_FAILURE = "EDIT_ITEMS_FAILURE";
export const EDIT_ITEMS_SUCCESS = "EDIT_ITEMS_SUCCESS";